import clsx from "clsx";
import React from "react";
import sectorsStyle from "./Sectors.module.css";
import { Button } from "@headlessui/react";
import Link from "next/link";
import { homeMenu } from "@/utils/constants";

const Sectors = () => {
  return (
    <section className="w-full flex flex-col">
      <div className="flex md:flex-row flex-col" id={homeMenu[0].link}>
        <div
          className={clsx(sectorsStyle["img-management"], "grow basis-1/2")}
        />
        <div className="grow basis-1/2 bg-[#3d5578] text-slate-100 p-[60px]">
          <div className="flex flex-col gap-4 text-center">
            <h1 className="text-xl font-bold">Management Consultancy</h1>
            <p>
              KERNEL International Ltd. works as a major consulting farm with a
              pool of professional experts in different areas of management
              consultancy. We thrive to conduct the most sophisticated way
              possible to manage projects from bona-fide clients....
            </p>
            <div>
              <Button
                className="bg-slate-500 px-4 py-2 rounded-full outline-0"
                as={Link}
                href="/consultancy"
              >
                Learn more
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className="flex md:flex-row flex-col" id={homeMenu[1].link}>
        <div className="grow basis-1/2 bg-[#6cbbc0] p-[60px]">
          <div className="flex flex-col gap-4 text-center">
            <h1 className="text-xl font-bold">
              Capacity Building & Technology Transfer
            </h1>
            <p>
              We conduct programs for capacity building and technology transfer
              via international organizations. We have been working extensively
              in the area of capacity building & human resource development for
              public and private sector officials.
            </p>
            <div>
              <Button
                className="bg-slate-500 px-4 py-2 rounded-full outline-0"
                as={Link}
                href="/capacity"
              >
                Learn more
              </Button>
            </div>
          </div>
        </div>
        <div className={clsx(sectorsStyle["img-capacity"], "grow basis-1/2")} />
      </div>
      <div className="flex md:flex-row flex-col" id={homeMenu[2].link}>
        <div className={clsx(sectorsStyle["img-research"], "grow basis-1/2")} />
        <div className="grow basis-1/2 bg-[#5b5b5b] text-slate-100 p-[60px]">
          <div className="flex flex-col gap-4 text-center">
            <h1 className="text-xl font-bold">Research & Development</h1>
            <p>
              It has extensive experience of implementing consultancy works
              generated by different national and international development
              projects. It has been more than 5 years; the consultant’s core
              team have been involved in implementing different development
              projects.
            </p>
            <div>
              <Button
                className="bg-slate-500 px-4 py-2 rounded-full outline-0"
                as={Link}
                href="/research"
              >
                Learn more
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Sectors;
