import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import PageWrapper from "@/components/layout/PageWrapper";

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kernel International Ltd.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(nunito.className, "antialiased")}>
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
